### ISSUE TITLE
Ships not using travel drive for attack command

### ISSUE THREAD

**Issue by MrSmite** [DeadAirRT/deadairaitweaks#1]
x4: 4.0 (CoH)
Mod: v1.02

Issue:

When you command an AI pilot to attack a target, they usually will not engage travel drive unless the target leaves the system. If they do engage the travel drive, they often drop out of it more than 50 km away.

They also will not engage travel drive if a target that was in firing range starts to flee. If you're using a M ship to attack a S ship, often that ship will escape.

Expected:

If an attack order is issued with a target out of range, the AI should use travel drive until it is within range. If during combat a target attempts to flee, the AI should engage travel drive until the target is in range again.

**Comment by DeadAirRT** [comment]
This may be fixed in v1.04. I made changes to a portion of the combat script that determines when they want to use travel drive to reposition. Previously, I had only made changes to move.generic thinking it was used for all of these scripts.

**Comment by MrSmite** [comment]
Thanks for the reply.

I haven't patched X4 to 4.20 yet because I haven't checked other mods I use for compatibility. If you want to close this that's fine. I can reopen if the problem still exists when I get around to updating.

**Comment by DeadAirRT** [comment]
Thank you. When you update, please let me know if you have any issues.
